Add angelbarrera92 challenge
do-community/kubernetes-challenge pull request #103
Opened 2021-12-26 10:09 UTC by angelbarrera92

Adding my challenge :)

Links:

- [angelbarrera92/do-k8s-challenge](https://github.com/angelbarrera92/do-k8s-challenge)
- [angelbarrera92/k8s-tunnel-controller](https://github.com/angelbarrera92/k8s-tunnel-controller)

2022-01-06 03:50 UTC, kimschles requested changes
Great work on your project, @angelbarrera92! 

In order for me to merge your PR, you'll need to add a license (MIT, Apache, BSD-2, BSD-3, or Commons Clause) to your [https://github.com/angelbarrera92/do-k8s-challenge](https://github.com/angelbarrera92/do-k8s-challenge) repo. Once that's added your project will be complete.

2022-01-10 08:20 UTC, angelbarrera92 commented
> Great work on your project, @angelbarrera92!
> 
> In order for me to merge your PR, you'll need to add a license (MIT, Apache, BSD-2, BSD-3, or Commons Clause) to your https://github.com/angelbarrera92/do-k8s-challenge repo. Once that's added your project will be complete.

Hi @kimschles, now everything should be fine :) Added Apache 2 License.

Regards

2022-01-10 10:54 UTC, OliverMensahDev approved these changes

2022-01-10 10:54 UTC, OliverMensahDev commented
Looks good to me.

2022-01-10 10:55 UTC, merged