Info about juggernaut's completed challenge
do-community/kubernetes-challenge pull request #115
Opened 2021-12-27 15:20 UTC by juggernaut

2022-01-06 18:14 UTC, OliverMensahDev requested changes
Awesome write-up @juggernaut 

Going through your write-up, I was wondering were you able to deploy your projects to There a DigitalOcean Managed Kubernetes cluster.  I didn't see any mention of  spinning up a DO Kubernetes Cluster

2022-01-12 16:10 UTC, juggernaut commented
@OliverMensahDev this post is sort of a continuation of my earlier posts on K8s. I mentioned spinning up a K8s cluster on DigitalOcean in my first post here - https://www.ameyalokare.com/technology/kubernetes/ci/cd/github-actions/2021/10/30/exploring-kubernetes-automated-deployment-part-1.html . Mentioning it again in this post seemed redundant.

2022-01-13 07:35 UTC, OliverMensahDev commented
I got it.

2022-01-13 07:35 UTC, OliverMensahDev approved these changes

2022-01-13 07:35 UTC, merged