Submission for kuberenetes challenge: GitOps CI/CD pipeline
do-community/kubernetes-challenge pull request #151
Opened 2021-12-29 14:47 UTC by nandajavarma

2022-01-06 23:57 UTC, OliverMensahDev approved these changes

2022-01-06 23:58 UTC, OliverMensahDev requested changes
Awesome work @nandajavarma.

With the steps, can you include some screenshots that show that you actually created the DOKS or screenshots of a few commands like `doctl` that you used?

2022-01-07 09:13 UTC, nandajavarma commented
Thanks for the review @OliverMensahDev ! I have added some screenshots of digital ocean UI to the [doc that explains creating a digital ocean cluster with terraform](https://github.com/nandajavarma/digital-ocean-k8s-challenge/blob/main/terraform/README.md). The terraform configs that use digitalocean provider are present in the same folder as the README. I hope this would suffice. let me know!

2022-01-07 09:29 UTC, OliverMensahDev approved these changes

2022-01-07 09:29 UTC, merged